<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CV</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">  
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="index.css" type="text/css" />
</head>
<body>
    <header class = "header">
        <h1>NOM Prénom</h1>
        <p>Intitulé du poste</p>
    </header>
    
    <main class = "main">
        <div class="mainsection">
            <section class="section1">
            <h2>Informations</h2>
            
            <h3>Contact</h3>
            
            <h4>Email</h4>
            <p>email@example.com</p>
            <h4>Téléphone</h4>
            <p>01 020 30 040 05</p>
            <h4>LinkedIn</h4>
            <a href="https://linkedin.com/example">https://linkedin.com/example</a>
            <h4>GitHub</h4>
            <a href="https://github.com/example">https://github.com/example</a>
            
            <h3>Biographie</h3>
            
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, eveniet, omnis fugit expedita aspernatur sint quos corrupti laborum quia sequi consectetur facilis enim ea! Eius quod harum aliquid error architecto.</p>
            
            <h3>Loisirs</h3>
            
            <ul>
                <li>Jeux de stratégie</li>
                <li>Violon</li>
                <li>Roller Derby</li>
                <li>Voile</li>
            </ul>
        </section>
        
        <section class="section2">
            <h2>Compétences</h2>
            
            <h3>Langages de programmation</h3>
            <ul>
                <li>HTML</li>
                <li>CSS</li>
                <li>JavaScript</li>
                <li>PHP</li>
                <li>SQL</li>
            </ul>
            
            <h3>Frameworks et Librairies</h3>
            <ul>
                <li>Sass</li>
                <li>Bootstrap</li>
                <li>Symfony</li>
                <li>Laravel</li>
            </ul>
            
            <h3>Logiciels</h3>
            <ul>
                <li>Photoshop</li>
                <li>Illustrator</li>
                <li>XD</li>
                <li>Figma</li>
            </ul>
            
            <h3>Langues</h3>
            <ul>
                <li>Anglais</li>
                <li>Français</li>
                <li>Arabe</li>
            </ul>
        </section>
        </div>
    </main>
</body>
</html>